name: PHP Composer

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ dev ]

jobs:
  check-phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

    - name: Verify MySQL connection from HOST
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port 32574 -uroot -ppassword -e "SHOW DATABASES"

    - uses: actions/checkout@v2

    - uses: php-actions/composer@v5

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: composer-

    - uses: php-actions/phpunit@v3

    - name: set-up php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0.11'
        extensions: imagick, pdo, pdo_mysql
 
    - name: version php
      run: php --version
    
    - name: Create token github
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo GITHUB_ACCESS_TOKEN
   

  check-phpstan:

    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: docker://oskarstark/phpstan-ga
          with:
              args: analyse src/
    
