name: PHP Composer

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v5
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - uses: php-actions/phpunit@v3

    - name: set-up php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0.11'
        extensions: imagick, pdo, pdo_mysql
 
    - name: version php
      run: php --version
    
    - name: Create run script
      run: |
        chmod +x ./install.sh
        ./install.sh
